module.exports = {
  projects: [
    '<rootDir>/apps/flight-app',
    '<rootDir>/apps/dashboard',
    '<rootDir>/apps/flight-admin',
    '<rootDir>/libs/logger-lib',
    '<rootDir>/libs/flight-lib',
    '<rootDir>/libs/dashboard-lib',
    '<rootDir>/libs/luggage/domain',
    '<rootDir>/apps/luggage',
    '<rootDir>/libs/luggage/feature-checkin',
    '<rootDir>/libs/luggage/feature-report-loss',
    '<rootDir>/libs/boarding/domain',
    '<rootDir>/apps/boarding',
    '<rootDir>/libs/boarding/feature-manage',
    '<rootDir>/libs/checkin/domain',
    '<rootDir>/apps/checkin',
    '<rootDir>/libs/checkin/feature-manage',
    '<rootDir>/libs/checkin/feature-upgrade',
    '<rootDir>/libs/checkin2/domain',
    '<rootDir>/apps/checkin2',
    '<rootDir>/libs/checkin2/feature-upgrade',
  ],
};
